### ISSUE TITLE
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

### ISSUE THREAD

**Issue by gnai** [MZehren/Automix#3]
```Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/Automix/automix/model/classes/track.py", line 281, in __init__
    self.features = featuresGetter(path)  # features dictionnary from the MIR estimators
  File "/home/user/Automix/automix/model/classes/track.py", line 35, in __init__
    self._estimators = self.getExecutionGraph()
  File "/home/user/Automix/automix/model/classes/track.py", line 52, in getExecutionGraph
    from automix.featureExtraction.beats.madmomBeatDetection import MadmomBeatDetection
  File "/home/user/Automix/automix/featureExtraction/beats/__init__.py", line 4, in <module>
    from .madmomBeatDetection import MadmomBeatDetection
  File "/home/user/Automix/automix/featureExtraction/beats/madmomBeatDetection.py", line 5, in <module>
    import madmom
  File "/home/user/.local/lib/python3.8/site-packages/madmom/__init__.py", line 24, in <module>
    from . import audio, evaluation, features, io, ml, models, processors, utils
  File "/home/user/.local/lib/python3.8/site-packages/madmom/audio/__init__.py", line 27, in <module>
    from . import comb_filters, filters, signal, spectrogram, stft
  File "madmom/audio/comb_filters.pyx", line 1, in init madmom.audio.comb_filters
```
  
  please help! Spent too much time trying to make this work. I have all the dependencies installed. and this is working for me: `madmomDrumsEnv/bin/python madmom-0.16.dev0/bin/DrumTranscriptor` 
  not sure what is still missing. numpy version outside of `madmomDrumsEnv` is 1.20.3 and in `madmomDrumsEnv` is 1.16.6. 
  I appreciate any tip to solve this. My environment is python3.8.10

**Comment by MZehren** [comment]
Hej, I will try to help you!

The program needs two different versions of Madmom to work: one for drum transcription, and one for beat detection. This is confusing, but sadly the algorithms for beat and drums estimation are in two different forks of madmom. Because I don't know how you can't install both versions in the same environment with pip, I did the ugly workaround of creating with the installation process the virtual environment "madmomDrumsEnv". This one seems to work for you. Now, you still require the version of madmom for the beat detection which seems to be the one raising the issue:
```
  File "/home/user/Automix/automix/featureExtraction/beats/madmomBeatDetection.py", line 5, in <module>
    import madmom
```

This one is not contained in the virtual environment "madmomDrumsEnv". Instead, its location depends on how you installed Automix. Could you check if madmom is correctly installed with:
`pip3 install . --editable`
The version should be 0.16.1

Good luck!

**Comment by gnai** [comment]
Hey @MZehren , 
First, let me say, that's a very interesting approach and paper! Congrats !
Really appreciate the help! 
Yes I have that version 
`Requirement already satisfied: madmom in /home/user/.local/lib/python3.8/site-packages (from AutoMix==0.1) (0.16.1)`
I even tried installing this `pip install pycocotools==2.0.0`  from some issues I've seen on Stack. thinking maybe it would solve. 
It should be able to read `.wav` and `.mp3` right?

**Comment by MZehren** [comment]
Ok, this is strange. Since the program fails when you load Madmom, I expect that you wouldn't be able to load Mamdom (the one _outside_ of the madmomDrumEnv) from your own code either. Can you replicate the issue somewhere else, or is it only when importing my file?

The software works with both .mp3 and .wav IIRC.

**Comment by gnai** [comment]
Hey Michael, 
I set up another venv and installed madmon again. Its working fine. Thank you ! :)

**Comment by MZehren** [comment]
Great to hear!
