### ISSUE TITLE
How can we create mix?

### ISSUE THREAD

**Issue by librem5** [MZehren/Automix#8]
Hello here
1. You can install two madmom version, just download and rename one of them, install separate like python setup.py install  and use like:
import madmom
import madmom_old

2. How we can make some mix,(cue is working we know) ?
I check what code is partial  ready(many TODO, empty function), can you put little manual step by step :

what im found:

trackBuilder.py(fully commented)
in ruleDriven.py i found generateMix, generateFX ... and other

but i cant find some roadmap or some plan( step by step what need TODO or some myMain.py how create mix)

**Comment by MZehren** [comment]
Hello,

1. Great, I might do that in the future.
2. There is no documentation for the mix generation because we did not publish on this. It is not officially supported by the current version of the software. 

if you want to get your hands dirty, here is a list of things to do to build mixes, that might not work:

```
from automix import config
from automix.model.classes.track import Track
from automix.model.inputOutput.serializer.reaperProxy import ReaperProxy
from automix.transition.mixManager import MixManager

tracks = [Track(path=path) for path in config.getFolderFiles("path to folder containing audio")]
mix = MixManager(tracks, overlap=32, startingTrack=tracks[0])
for track in mix.tracks:
        track.takeMarkers = [{"time": time - 0.1, "color": "r", "label": "in"} for time in track.getCueIns().times]
        track.takeMarkers += [{"time": time - 0.1, "color": "b", "label": "out"} for time in track.getCueOuts().times]
ReaperProxy().serialize("test.RPP", tracks=mix.tracks, markers=mix.markers)
```

This should generate a file that you can open in Reaper v6.x. But it might fail, again, since it is not tested and officially supported.

Good luck

**Comment by librem5** [comment]
Hello again, thx for response, ofc i will try with dirty hands ;) 

Also same project https://github.com/ChenPaulYu/DJtransGAN (https://github.com/ChenPaulYu/DJtransGAN-dg-pipeline), all works fine with music puzzle but cue point not correct, you can check some options and it can help on future you and your project Automix
King regard's ...
